name: Blog CI
on:
  push:
    branches:
      - main

jobs:
  page-generator:
    name: Generating pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install dependencies
        run: pnpm install
      - name: Build pages
        run: pnpm run build
      - name: Deploy to website
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          git-config-name: Lukaka
          git-config-email: monishine_code@163.com
          repository-name: monishine/website
          token: ${{ secrets.LUKAKASITE_BOT_TOKEN }}
          branch: main # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
          target-folder: docs/blog
          clean: true # Automatically remove deleted files from the deploy branch
          commit-message: update from Blog
